# Generated by Django 4.0.10 on 2023-06-20 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='標題')),
                ('tags', models.CharField(max_length=50, verbose_name='關鍵字(空白分隔)')),
                ('name', models.CharField(max_length=50, verbose_name='英文標籤名稱')),
                ('description', models.CharField(max_length=250, verbose_name='說明')),
                ('classify_type', models.CharField(choices=[('線上課程', '線上課程'), ('文章主題', '文章主題')], default='', max_length=4, verbose_name='類型')),
                ('cover_image', models.CharField(max_length=250, verbose_name='封面圖片檔案名稱')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='最后修改日期')),
                ('created_time', models.DateTimeField(auto_now=True, verbose_name='保存日期')),
            ],
        ),
        migrations.CreateModel(
            name='Coursechapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='標題')),
                ('number', models.IntegerField(verbose_name='章節編號')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='最后修改日期')),
                ('created_time', models.DateTimeField(auto_now=True, verbose_name='保存日期')),
                ('classification_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.classification', verbose_name='章節分類')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='標題')),
                ('tags', models.CharField(max_length=50, verbose_name='關鍵字(空白分隔)')),
                ('description', models.CharField(max_length=250, verbose_name='說明')),
                ('cover_image', models.CharField(max_length=50, verbose_name='封面圖片檔案名稱')),
                ('number', models.IntegerField(null=True, verbose_name='章節課程編號')),
                ('article_file', models.CharField(max_length=150, verbose_name='文章檔案名稱')),
                ('download_url', models.URLField(blank=True, verbose_name='下載網址')),
                ('video_url', models.URLField(blank=True, verbose_name='影片網址')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='最后修改日期')),
                ('created_time', models.DateTimeField(auto_now=True, verbose_name='保存日期')),
                ('classification_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.classification', verbose_name='文章分類')),
                ('coursechapter_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.coursechapter', verbose_name='文章章節')),
            ],
        ),
    ]
