# Generated by Django 4.0.10 on 2023-07-06 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default=1, upload_to='image/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='coursechapter_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.coursechapter', verbose_name='文章章節'),
        ),
        migrations.AlterField(
            model_name='article',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='章節課程編號'),
        ),
    ]
