# Generated by Django 4.0.10 on 2023-07-06 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_article_image_alter_article_coursechapter_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
        migrations.AlterField(
            model_name='article',
            name='article_file',
            field=models.FileField(upload_to='static/upload/markdown/', verbose_name='文章檔案名稱'),
        ),
        migrations.AlterField(
            model_name='article',
            name='cover_image',
            field=models.ImageField(upload_to='static/upload/image/', verbose_name='封面圖片檔案名稱'),
        ),
        migrations.AlterField(
            model_name='classification',
            name='cover_image',
            field=models.ImageField(upload_to='static/upload/image/', verbose_name='封面圖片檔案名稱'),
        ),
    ]
