# Generated by Django 4.0.10 on 2024-03-09 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_article_image_alter_article_article_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.TextField(max_length=99999, verbose_name='內容')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='最后修改日期')),
                ('created_time', models.DateTimeField(auto_now=True, verbose_name='保存日期')),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(max_length=200, verbose_name='說明'),
        ),
        migrations.AlterField(
            model_name='classification',
            name='description',
            field=models.TextField(max_length=200, verbose_name='說明'),
        ),
    ]
